pipeline {
    agent {
        docker {
            image 'python:3.11'
            args '--network=host'
        }
    }
    environment {
        HOME = "${env.WORKSPACE}@tmp"
        BIN_PATH = "${HOME}/.local/bin/"
    }
    stages {
        stage('Git Clone') {
            steps {
                git changelog: false, url: 'http://AlexanderTer:Zghjuhfvvbcn15243@gitlab.devops.ru/AlexanderTer/app'
            }
        }
        stage('Prepare') {
            steps {
                sh 'pip install virtualenv'
                sh "${BIN_PATH}virtualenv venv"
                sh 'bash -c "source venv/bin/activate"'
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps{
                sh 'python -m unittest discover -s "./tests" -p "test.py"'
                sh "${BIN_PATH}flake8 ."
                sh "${BIN_PATH}mypy ."
            }
        }
    }
}